"""
TensorLoom Code Emitter — Utility for generating clean, formatted Python code.

Provides an indentation-aware writer that the PyTorch backend uses to
produce readable, properly formatted Python source.
"""
from __future__ import annotations


class CodeEmitter:
    """Builds a Python source string with automatic indentation management."""

    def __init__(self, indent_str: str = "    ") -> None:
        self._lines: list[str] = []
        self._indent_level = 0
        self._indent_str = indent_str
        self._imports: set[str] = set()

    # ── Indentation ───────────────────────────────────────────

    def indent(self) -> None:
        self._indent_level += 1

    def dedent(self) -> None:
        self._indent_level = max(0, self._indent_level - 1)

    # ── Writing ───────────────────────────────────────────────

    def line(self, text: str = "") -> None:
        """Write a single line with current indentation."""
        if text:
            self._lines.append(f"{self._indent_str * self._indent_level}{text}")
        else:
            self._lines.append("")

    def blank(self) -> None:
        """Write a blank line."""
        self._lines.append("")

    def comment(self, text: str) -> None:
        """Write a Python comment."""
        self.line(f"# {text}")

    def docstring(self, text: str) -> None:
        """Write a triple-quoted docstring."""
        self.line(f'"""{text}"""')

    # ── Import Tracking ──────────────────────────────────────

    def add_import(self, import_line: str) -> None:
        """Register an import; duplicates are automatically removed."""
        self._imports.add(import_line)

    # ── Output ────────────────────────────────────────────────

    def build(self) -> str:
        """Return the complete Python source as a string."""
        header: list[str] = []

        # Generated file header
        header.append('"""Auto-generated by TensorLoom Compiler (tlc) v0.1.0"""')
        header.append("")

        # Deduplicated, sorted imports
        if self._imports:
            for imp in sorted(self._imports):
                header.append(imp)
            header.append("")

        return "\n".join(header + self._lines) + "\n"
