"""Auto-generated by TensorLoom Compiler (tlc) v0.1.0"""

import torch
import torch.nn as nn


# ═══ Device Configuration ═══
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"TensorLoom Runtime — device: {device}")

x = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32, device=device)
y = torch.tensor([4.0, 5.0, 6.0], dtype=torch.float32, device=device)
z = (x @ y + 0.5)
scaled = (z * 2.0)
activated = torch.relu(scaled)
print(activated)
