"""Auto-generated by TensorLoom Compiler (tlc) v0.1.0"""

from torch.amp import autocast, GradScaler
from torch.utils.data import DataLoader, TensorDataset
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


# ═══ Device Configuration ═══
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"TensorLoom Runtime — device: {device}")


# === NML Import: lstm_seq2seq.nml as SeqModel ===

# === NML Model: SeqModel ===

class SeqModel(nn.Module):
    """NML declarative model: SeqModel
    Auto-generated from .nml specification."""

    def __init__(self, vocab_size=5000, embed_dim=256, hidden_dim=512, num_layers=2):
        super().__init__()
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers

        self.embedding = nn.Embedding(self.vocab_size, self.embed_dim)
        self.lstm = nn.LSTM(self.embed_dim, self.hidden_dim, num_layers=self.num_layers, batch_first=True)
        self.fc_out = nn.Linear(self.hidden_dim, self.vocab_size)

    def forward(self, x):
        x = self.embedding(x)
        x = self.lstm(x)
        x = self.fc_out(x)
        return x



net = SeqModel(vocab_size=10000, hidden_dim=1024).to(device)
net = torch.compile(net, mode="max-autotune")  # TensorLoom: Automatic Kernel Fusion

data = load_dataset()

# ═══ TensorLoom Training Block ═══
optimizer = optim.Adam(net.parameters(), lr=0.0003)
criterion = nn.CrossEntropyLoss()
scaler = GradScaler("cuda")


for epoch in range(15):
    net.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for batch_idx, (inputs, targets) in enumerate(data):
        inputs, targets = inputs.to(device), targets.to(device)
        optimizer.zero_grad()

        with autocast(device_type='cuda', dtype=torch.float16):
            outputs = net(inputs)
            loss = criterion(outputs, targets)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += targets.size(0)
        correct += predicted.eq(targets).sum().item()

    epoch_loss = running_loss / max(total, 1)
    accuracy = correct / max(total, 1)

print("\nTraining complete.")

