"""Auto-generated by TensorLoom Compiler (tlc) v0.1.0"""

import torch
import torch.nn as nn
import torch.nn.functional as F


# ═══ Device Configuration ═══
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"TensorLoom Runtime — device: {device}")


# === NML Model: LSTMEncoder ===

class LSTMEncoder(nn.Module):
    """NML declarative model: LSTMEncoder
    Auto-generated from .nml specification."""

    def __init__(self, vocab_size=5000, embed_dim=256, hidden_dim=512, num_layers=2):
        super().__init__()
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers

        self.embedding = nn.Embedding(self.vocab_size, self.embed_dim)
        self.lstm = nn.LSTM(self.embed_dim, self.hidden_dim, num_layers=self.num_layers, batch_first=True)
        self.fc_out = nn.Linear(self.hidden_dim, self.vocab_size)

    def forward(self, x):
        x = self.embedding(x)
        x = self.lstm(x)
        x = self.fc_out(x)
        return x


