"""Auto-generated by TensorLoom Compiler (tlc) v0.1.0"""

from torch.amp import autocast, GradScaler
from torch.utils.checkpoint import checkpoint as activation_checkpoint
from torch.utils.data import DataLoader, TensorDataset
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


# ═══ Device Configuration ═══
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"TensorLoom Runtime — device: {device}")

# TensorLoom import: data.mnist
# TensorLoom import: nn

class MNISTClassifier(nn.Module):
    """TensorLoom model: MNISTClassifier"""

    def __init__(self):
        super().__init__()
        self.input = nn.Linear(784, 256)
        self.hidden = nn.Linear(256, 128)
        self.output = nn.Linear(128, 10)

    def _forward_body(self, x):
        # Actual computation (activations are recomputed during backward)
        x = torch.nn.functional.dropout(torch.relu(self.input(x)), p=0.2, training=self.training)
        x = torch.nn.functional.dropout(torch.relu(self.hidden(x)), p=0.2, training=self.training)
        x = torch.softmax(self.output(x), dim=-1)
        return x

    def forward(self, x):
        """Gradient-checkpointed forward — trades compute for ~60%% less activation memory."""
        return activation_checkpoint(self._forward_body, x, use_reentrant=False)


net = MNISTClassifier().to(device)
net = torch.compile(net, mode="max-autotune")  # TensorLoom: Automatic Kernel Fusion

data = mnist.load(batch_size=64, shuffle=True)

# ═══ TensorLoom Training Block ═══
optimizer = optim.Adam(net.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()
scaler = GradScaler("cuda")


for epoch in range(10):
    net.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for batch_idx, (inputs, targets) in enumerate(data):
        inputs, targets = inputs.to(device), targets.to(device)
        optimizer.zero_grad()

        with autocast(device_type='cuda', dtype=torch.float16):
            outputs = net(inputs)
            loss = criterion(outputs, targets)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += targets.size(0)
        correct += predicted.eq(targets).sum().item()

    epoch_loss = running_loss / max(total, 1)
    accuracy = correct / max(total, 1)

    # Weight Snapshot — periodic model backup
    if (epoch + 1) % 2 == 0:
        torch.save(net.state_dict(), f"checkpoint_epoch_{epoch+1}.pt")
        print(f"  [snapshot] Saved checkpoint_epoch_{epoch+1}.pt")

    # Callback: epoch_end
    class _Metrics: pass
    metrics = _Metrics()
    metrics.epoch = epoch + 1
    metrics.loss = epoch_loss
    metrics.accuracy = accuracy
    print(f"Epoch {metrics.epoch}: loss={metrics.loss:.4f}, acc={metrics.accuracy:.2%}")

print("\nTraining complete.")

