"""Auto-generated by TensorLoom Compiler (tlc) v0.1.0"""

from torch.amp import autocast, GradScaler
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.checkpoint import checkpoint as activation_checkpoint
from torch.utils.data import DataLoader, TensorDataset
from torch.utils.data.distributed import DistributedSampler
import os
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim



# ═══ TensorLoom Distributed Data Parallel (DDP) ═══

def setup_ddp():
    """Initialize distributed process group. Auto-injected by TensorLoom."""
    dist.init_process_group(backend="nccl", init_method="env://")
    local_rank = int(os.environ["LOCAL_RANK"])
    torch.cuda.set_device(local_rank)
    return local_rank

def cleanup_ddp():
    """Tear down distributed process group."""
    dist.destroy_process_group()

# TensorLoom import: data.mnist
# TensorLoom import: nn

class MNISTClassifier(nn.Module):
    """TensorLoom model: MNISTClassifier"""

    def __init__(self):
        super().__init__()
        self.input = nn.Linear(784, 256)
        self.hidden = nn.Linear(256, 128)
        self.output = nn.Linear(128, 10)

    def _forward_body(self, x):
        # Actual computation (activations are recomputed during backward)
        x = torch.nn.functional.dropout(torch.relu(self.input(x)), p=0.2, training=self.training)
        x = torch.nn.functional.dropout(torch.relu(self.hidden(x)), p=0.2, training=self.training)
        x = torch.softmax(self.output(x), dim=-1)
        return x

    def forward(self, x):
        """Gradient-checkpointed forward — trades compute for ~60%% less activation memory."""
        return activation_checkpoint(self._forward_body, x, use_reentrant=False)



def train_distributed():
    """Main distributed training entry point. Launch with torchrun."""
    local_rank = setup_ddp()
    print(f"TensorLoom DDP -- rank={dist.get_rank()}/{dist.get_world_size()} on GPU {local_rank}")

    # Model instantiation with DDP wrapping
    net = MNISTClassifier().to(local_rank)
    net = torch.compile(net, mode="max-autotune")  # TensorLoom: Automatic Kernel Fusion
    net = DDP(net, device_ids=[local_rank])


    # ═══ Distributed Training Loop ═══
    # Distributed sampler — ensures each GPU gets unique data slices
    sampler = DistributedSampler(
        data,
        num_replicas=dist.get_world_size(),
        rank=dist.get_rank(),
        shuffle=True,
    )
    loader = DataLoader(data, batch_size=64, sampler=sampler)

    optimizer = optim.Adam(net.parameters(), lr=0.001)
    criterion = nn.CrossEntropyLoss()
    scaler = GradScaler("cuda")

    for epoch in range(10):
        # Critical: re-shuffle data across ranks each epoch
        sampler.set_epoch(epoch)

        net.train()
        running_loss = 0.0
        correct = 0
        total = 0

        for batch_idx, (inputs, targets) in enumerate(loader):
            inputs, targets = inputs.to(local_rank), targets.to(local_rank)
            optimizer.zero_grad()

            with autocast(device_type='cuda', dtype=torch.float16):
                outputs = net(inputs)
                loss = criterion(outputs, targets)

            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()

            running_loss += loss.item()
            _, predicted = outputs.max(1)
            total += targets.size(0)
            correct += predicted.eq(targets).sum().item()

        epoch_loss = running_loss / max(total, 1)
        accuracy = correct / max(total, 1)

        # Weight Snapshot — only rank 0 saves
        if dist.get_rank() == 0 and (epoch + 1) % 2 == 0:
            torch.save(net.module.state_dict(), f"checkpoint_epoch_{epoch+1}.pt")
            print(f"  [snapshot] Saved checkpoint_epoch_{epoch+1}.pt")

        if dist.get_rank() == 0:

            # Callback: epoch_end
            class _Metrics: pass
            metrics = _Metrics()
            metrics.epoch = epoch + 1
            metrics.loss = epoch_loss
            metrics.accuracy = accuracy
            print(f"Epoch {metrics.epoch}: loss={metrics.loss:.4f}, acc={metrics.accuracy:.2%}")

    if dist.get_rank() == 0:
        print("\nDistributed training complete.")

    cleanup_ddp()


# ═══ Entry Point ═══
# Launch: torchrun --nproc_per_node=NUM_GPUS script.py
if __name__ == "__main__":
    if "LOCAL_RANK" in os.environ:
        train_distributed()
    else:
        print("[TensorLoom] Launch with: torchrun --nproc_per_node=<NUM_GPUS> " + __file__)
        print("             Falling back to single-GPU mode.")
        # Single-GPU fallback
        os.environ["LOCAL_RANK"] = "0"
        os.environ["RANK"] = "0"
        os.environ["WORLD_SIZE"] = "1"
        os.environ["MASTER_ADDR"] = "localhost"
        os.environ["MASTER_PORT"] = "29500"
        train_distributed()

