"""Auto-generated by TensorLoom Compiler (tlc) v0.1.0"""

import torch
import torch.nn as nn
import torch.nn.functional as F


# ═══ Device Configuration ═══
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"TensorLoom Runtime — device: {device}")


# === NML Model: ResBlock ===

class ResBlock(nn.Module):
    """NML declarative model: ResBlock
    Auto-generated from .nml specification."""

    def __init__(self, channels=64):
        super().__init__()
        self.channels = channels

        self.conv1 = nn.Conv2d(self.channels, self.channels, kernel_size=3, stride=1, padding=1)
        self.bn1 = nn.BatchNorm2d(self.channels)
        self.conv2 = nn.Conv2d(self.channels, self.channels, kernel_size=3, stride=1, padding=1)
        self.bn2 = nn.BatchNorm2d(self.channels)

    def forward(self, x):
        residual = x
        x = self.conv1(x)
        x = self.bn1(x)
        x = relu(x)
        x = self.conv2(x)
        x = self.bn2(x)
        x = relu((x + residual))
        return x


