"""Auto-generated by TensorLoom Compiler (tlc) v0.1.0"""

from torch.amp import autocast, GradScaler
from torch.utils.checkpoint import checkpoint as activation_checkpoint
from torch.utils.data import DataLoader, TensorDataset
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


# ═══ Device Configuration ═══
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"TensorLoom Runtime — device: {device}")


# === NML Import: resnet.nml as ResBlock ===

# === NML Model: ResBlock ===

class ResBlock(nn.Module):
    """NML declarative model: ResBlock
    Auto-generated from .nml specification."""

    def __init__(self, channels=64):
        super().__init__()
        self.channels = channels

        self.conv1 = nn.Conv2d(self.channels, self.channels, kernel_size=3, stride=1, padding=1)
        self.bn1 = nn.BatchNorm2d(self.channels)
        self.conv2 = nn.Conv2d(self.channels, self.channels, kernel_size=3, stride=1, padding=1)
        self.bn2 = nn.BatchNorm2d(self.channels)

    def forward(self, x):
        residual = x
        x = self.conv1(x)
        x = self.bn1(x)
        x = relu(x)
        x = self.conv2(x)
        x = self.bn2(x)
        x = relu((x + residual))
        return x



net = ResBlock(channels=128).to(device)
net = torch.compile(net, mode="max-autotune")  # TensorLoom: Automatic Kernel Fusion

data = load_dataset()

# ═══ TensorLoom Training Block ═══
optimizer = optim.Adam(net.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()
scaler = GradScaler("cuda")


for epoch in range(20):
    net.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for batch_idx, (inputs, targets) in enumerate(data):
        inputs, targets = inputs.to(device), targets.to(device)
        optimizer.zero_grad()

        with autocast(device_type='cuda', dtype=torch.float16):
            outputs = net(inputs)
            loss = criterion(outputs, targets)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += targets.size(0)
        correct += predicted.eq(targets).sum().item()

    epoch_loss = running_loss / max(total, 1)
    accuracy = correct / max(total, 1)

    # Weight Snapshot — periodic model backup
    if (epoch + 1) % 5 == 0:
        torch.save(net.state_dict(), f"checkpoint_epoch_{epoch+1}.pt")
        print(f"  [snapshot] Saved checkpoint_epoch_{epoch+1}.pt")

print("\nTraining complete.")

