"""Auto-generated by TensorLoom Compiler (tlc) v0.1.0"""

from torch.amp import autocast, GradScaler
from torch.utils.data import DataLoader, TensorDataset
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


# ═══ Device Configuration ═══
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"TensorLoom Runtime — device: {device}")


# === NML Import: transformer.nml as MyTransformer ===

# === NML Model: MyTransformer ===

class MyTransformer(nn.Module):
    """NML declarative model: MyTransformer
    Auto-generated from .nml specification."""

    def __init__(self, d_model=512, n_heads=8, dropout_rate=0.1):
        super().__init__()
        self.d_model = d_model
        self.n_heads = n_heads
        self.dropout_rate = dropout_rate

        self.attention = nn.MultiheadAttention(self.d_model, self.n_heads)
        self.norm1 = nn.LayerNorm(self.d_model)
        self.norm2 = nn.LayerNorm(self.d_model)
        self.ff = nn.Linear(self.d_model, self.d_model)
        self.dropout = nn.Dropout(self.dropout_rate)

    def forward(self, x):
        residual = x
        x = self.norm1(x)
        x = (residual + self.dropout(self.attention(x)))
        residual2 = x
        x = self.norm2(x)
        x = (residual2 + self.dropout(self.ff(x)))
        return x



net = MyTransformer(d_model=256, n_heads=4).to(device)
net = torch.compile(net, mode="max-autotune")  # TensorLoom: Automatic Kernel Fusion

data = load_dataset()

# ═══ TensorLoom Training Block ═══
optimizer = optim.Adam(net.parameters(), lr=0.0001)
criterion = nn.CrossEntropyLoss()
scaler = GradScaler("cuda")


for epoch in range(5):
    net.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for batch_idx, (inputs, targets) in enumerate(data):
        inputs, targets = inputs.to(device), targets.to(device)
        optimizer.zero_grad()

        with autocast(device_type='cuda', dtype=torch.float16):
            outputs = net(inputs)
            loss = criterion(outputs, targets)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += targets.size(0)
        correct += predicted.eq(targets).sum().item()

    epoch_loss = running_loss / max(total, 1)
    accuracy = correct / max(total, 1)

print("\nTraining complete.")

