"""Auto-generated by TensorLoom Compiler (tlc) v0.1.0"""

import torch
import torch.nn as nn
import torch.nn.functional as F


# ═══ Device Configuration ═══
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"TensorLoom Runtime — device: {device}")


# === NML Model: TransformerBlock ===

class TransformerBlock(nn.Module):
    """NML declarative model: TransformerBlock
    Auto-generated from .nml specification."""

    def __init__(self, d_model=512, n_heads=8, dropout_rate=0.1):
        super().__init__()
        self.d_model = d_model
        self.n_heads = n_heads
        self.dropout_rate = dropout_rate

        self.attention = nn.MultiheadAttention(self.d_model, self.n_heads)
        self.norm1 = nn.LayerNorm(self.d_model)
        self.norm2 = nn.LayerNorm(self.d_model)
        self.ff = nn.Linear(self.d_model, self.d_model)
        self.dropout = nn.Dropout(self.dropout_rate)

    def forward(self, x):
        residual = x
        x = self.norm1(x)
        x = (residual + self.dropout(self.attention(x)))
        residual2 = x
        x = self.norm2(x)
        x = (residual2 + self.dropout(self.ff(x)))
        return x


