"""Auto-generated by TensorLoom Compiler (tlc) v0.1.0"""

import torch
import torch.nn as nn
import triton
import triton.language as tl


# ═══ Device Configuration ═══
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"TensorLoom Runtime — device: {device}")


# ═══ TensorLoom Triton Kernel: vector_add ═══

@triton.jit
def vector_add(x_ptr, y_ptr, z_ptr, num_elements, BLOCK_SIZE: tl.constexpr):
    """TensorLoom Triton kernel: vector_add"""
    pid = tl.program_id(axis=0)
    block_start = (pid * BLOCK_SIZE)
    offsets = (block_start + tl.arange(0, BLOCK_SIZE))
    mask = (offsets < num_elements)
    x = tl.load((x_ptr + offsets), mask=mask)
    y = tl.load((y_ptr + offsets), mask=mask)
    z = (x + y)
    tl.store((z_ptr + offsets), z, mask=mask)

def vector_add_launcher(x, y, z, num_elements, BLOCK_SIZE=1024):
    """Auto-generated launcher for Triton kernel 'vector_add'.
    Computes grid dimensions and dispatches the kernel."""
    grid = lambda meta: (triton.cdiv(num_elements, meta['BLOCK_SIZE']),)
    z = torch.empty_like(x)
    vector_add[grid](x, y, z, num_elements, BLOCK_SIZE=BLOCK_SIZE)
    return z

