"""Auto-generated by TensorLoom Compiler (tlc) v0.1.0"""

from torch.amp import autocast, GradScaler
from torch.utils.checkpoint import checkpoint as activation_checkpoint
from torch.utils.data import DataLoader, TensorDataset
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


# ═══ Device Configuration ═══
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"TensorLoom Runtime — device: {device}")


# === NML Import: vision_transformer.nml as ViT ===

# === NML Model: ViT ===

class ViT(nn.Module):
    """NML declarative model: ViT
    Auto-generated from .nml specification."""

    def __init__(self, in_channels=3, patch_size=16, embed_dim=768, num_heads=12, num_classes=1000):
        super().__init__()
        self.in_channels = in_channels
        self.patch_size = patch_size
        self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.num_classes = num_classes

        self.patch_embed = nn.Conv2d(self.in_channels, self.embed_dim, kernel_size=self.patch_size, stride=self.patch_size)
        self.norm1 = nn.LayerNorm(self.embed_dim)
        self.attention = nn.MultiheadAttention(self.embed_dim, self.num_heads)
        self.norm2 = nn.LayerNorm(self.embed_dim)
        self.mlp_fc1 = nn.Linear(self.embed_dim, self.embed_dim)
        self.mlp_fc2 = nn.Linear(self.embed_dim, self.num_classes)

    def forward(self, x):
        x = self.patch_embed(x)
        x = self.norm1(x)
        residual = x
        x = (residual + self.attention(x))
        x = self.norm2(x)
        x = self.mlp_fc1(x)
        x = relu(x)
        x = self.mlp_fc2(x)
        return x



net = ViT(embed_dim=384, num_heads=6, num_classes=100).to(device)
net = torch.compile(net, mode="max-autotune")  # TensorLoom: Automatic Kernel Fusion

data = load_dataset()

# ═══ TensorLoom Training Block ═══
optimizer = optim.Adam(net.parameters(), lr=0.0001)
criterion = nn.CrossEntropyLoss()
scaler = GradScaler("cuda")


for epoch in range(30):
    net.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for batch_idx, (inputs, targets) in enumerate(data):
        inputs, targets = inputs.to(device), targets.to(device)
        optimizer.zero_grad()

        with autocast(device_type='cuda', dtype=torch.float16):
            outputs = net(inputs)
            loss = criterion(outputs, targets)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += targets.size(0)
        correct += predicted.eq(targets).sum().item()

    epoch_loss = running_loss / max(total, 1)
    accuracy = correct / max(total, 1)

    # Weight Snapshot — periodic model backup
    if (epoch + 1) % 10 == 0:
        torch.save(net.state_dict(), f"checkpoint_epoch_{epoch+1}.pt")
        print(f"  [snapshot] Saved checkpoint_epoch_{epoch+1}.pt")

print("\nTraining complete.")

