"""Auto-generated by TensorLoom Compiler (tlc) v0.1.0"""

import torch
import torch.nn as nn
import torch.nn.functional as F


# ═══ Device Configuration ═══
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"TensorLoom Runtime — device: {device}")


# === NML Model: ViT ===

class ViT(nn.Module):
    """NML declarative model: ViT
    Auto-generated from .nml specification."""

    def __init__(self, in_channels=3, patch_size=16, embed_dim=768, num_heads=12, num_classes=1000):
        super().__init__()
        self.in_channels = in_channels
        self.patch_size = patch_size
        self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.num_classes = num_classes

        self.patch_embed = nn.Conv2d(self.in_channels, self.embed_dim, kernel_size=self.patch_size, stride=self.patch_size)
        self.norm1 = nn.LayerNorm(self.embed_dim)
        self.attention = nn.MultiheadAttention(self.embed_dim, self.num_heads)
        self.norm2 = nn.LayerNorm(self.embed_dim)
        self.mlp_fc1 = nn.Linear(self.embed_dim, self.embed_dim)
        self.mlp_fc2 = nn.Linear(self.embed_dim, self.num_classes)

    def forward(self, x):
        x = self.patch_embed(x)
        x = self.norm1(x)
        residual = x
        x = (residual + self.attention(x))
        x = self.norm2(x)
        x = self.mlp_fc1(x)
        x = relu(x)
        x = self.mlp_fc2(x)
        return x


